### ISSUE TITLE
0.15.0+ makes Webpack load slowly

### ISSUE THREAD

**Issue by ljconde** [webpack-contrib/css-loader#124]
Ever since the 0.15.0 update, I've had to revert back to 0.14.5, because Webpack loads very slowly (12 secs vs almost 60 secs). Is there a breaking change I should be aware of? Maybe something regarding PostCSS?

**Comment by ljconde** [comment]
Here's the webpack update output using css-loader 0.16.0 (same happens with 0.15.0+):
> Hash: 8d3652a9b4988c8ad221
> Version: webpack 1.11.0
> Time: **51612ms**

Here's the output with css-loader 0.14.5:
> Hash: bd471e6f4aa10b195feb
> Version: webpack 1.11.0
> Time: **6121ms**

**Comment by BowlingX** [comment]
Same here, but I have more then 40 css (sass) modules, that take about 15 seconds with the old version and around 4 Minutes with the latest.

**Comment by ljconde** [comment]
Looks like this is fixed in 0.18.0 (at least for me). @BowlingX can you confirm if it's fixed for you as well?

**Comment by BowlingX** [comment]
still exists in 0.18, but its faster then the 0.16 build:

## 0.18.0:

> Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Hash: 0a92ccc4450f1a9a5193
Version: webpack 1.12.0
Time: **60275ms**

## 0.14.5

> Hash: 53d6260b86ff835b0eb1
Version: webpack 1.12.0
Time: **16196ms**

**Comment by Phoenixmatrix** [comment]
Probably PostCSS, since that's the first thing that changed after 0.14.5, and that thing does a lot.

IMO at this point CSS loader does too much. There's no real alternatives if you want url/import mapping and sourcemaps (raw-loader won't help with those), but to get those you have to pay the cost of all the bells and whistles. Is it time for a minimal css-loader that does just enough to pass stuff from the post-processors (like less-loader, sass-loader, etc) to style-loader as quickly as possible, with optional import/url support?

**Comment by jhnns** [comment]
I agree @Phoenixmatrix. There are still a lot of people who only want imports and urls to be resolved which doesn't even require an actual parser imho.

What do you think @sokra? Is it time to separate the css-loader from css-modules? Did I miss something?

**Comment by sars** [comment]
same problem...

**Comment by unindented** [comment]
Same problem here. With `0.14.5` build time is 60s, with `0.23.1` it is 90s.

**Comment by MoOx** [comment]
poke @ai

**Comment by ai** [comment]
New PostCSS is not slow then previous. But when you use depreacted PostCSS API it is of course slower, because it should print warning and call extra code.

So, you should update webpack custom plugins for PostCSS 5.0 API (it is very simple) to remove all warnings. It will give a good speed boost.

**Comment by ai** [comment]
Here is benchmarks: [PostCSS 4.x](https://github.com/postcss/benchmark/tree/e5d50dd121b4a181cc77205a4d15a9f253b034df#preprocessors) vs. [5.0](https://github.com/postcss/benchmark#preprocessors).

**Comment by ElegantScripting** [comment]
I'm having these issues too.

**Comment by goldensunliu** [comment]
@ai do you know which calls in https://github.com/webpack/css-loader/blob/master/lib/processCss.js are deprecated? I would take a stab at it, but am having trouble finding any information on deprecated methods from 4.0

**Comment by goldensunliu** [comment]
I am not seeing anything in the source code that is deprecated based on this change log on deprecation 
https://github.com/postcss/postcss/blob/0873667be6d65dafb1d2a3650ce87cd1f3fec204/CHANGELOG.md#50-president-valac

**Comment by ai** [comment]
@goldensunliu here is 5.0 changes post https://github.com/postcss/postcss/releases/tag/5.0.0

Maybe CSS Modules uses 4.0 API?

**Comment by unindented** [comment]
@ai `css-loader` didn't use to use PostCSS, just regular expressions. It was version `0.15` the one that introduced PostCSS, and that's when performance degraded. I don't think it's a matter of 4.0 API vs 5.0 API. It's just that `css-loader` wasn't using PostCSS, and was obviously faster, because it did less.

**Comment by Phoenixmatrix** [comment]
I still feel there's more to it than just "css-loader is using PostCSS so now its slow"

PostCSS is reasonably fast. Using a couple of postcss things with raw loader is significantly faster than using css-loader stand alone. so I don't think it's just PostCSS usage.

**Comment by ai** [comment]
We have a postcss-devtools to find slowest plugin in PostCSS pipeline https://github.com/postcss/postcss-devtools

I think it is a ideal case for it.

**Comment by billyjanitsch** [comment]
@ai I tried [adding `postcss-devtools` to the `css-loader` pipeline](https://github.com/billyjanitsch/css-loader/commit/510b18e21a92812085edcf6b89cbc683fd8b9df7) but it throws a rather unhelpful error:

```
Module build failed: TypeError: Cannot read property 'length' of undefined
```

Any ideas?

**Comment by ai** [comment]
@billyjanitsch we need a full stacktrace to fix this issue

**Comment by billyjanitsch** [comment]
@ai I figured out that it's because `postcss-modules-values` (also included in the `css-loader` pipeline) [doesn't register itself](https://github.com/css-modules/postcss-modules-values/blob/master/src/index.js#L11) using the `postcss.plugin` API.

Is this valid (i.e. a bug in `postcss-devtools` for not handling this case) or invalid (i.e. a bug in `postcss-modules-values` for not registering itself [like others do](https://github.com/css-modules/postcss-modules-local-by-default/blob/master/index.js#L200))?

**Comment by ai** [comment]
It is bad thing for public plugins https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin

But we should fix it in postcss-devtools, because some debug/custom plugins could be without name.

**Comment by billyjanitsch** [comment]
Anyway, I was able to hackily fix this for the purpose of debugging `css-loader` speed, and found that in our build, `postcss-modules-scope` is by far the slowest plugin in the pipeline. `postcss-modules-local-by-default` can also be sluggish.

If anyone has more time to work on this, looking for [perf improvements there](https://github.com/css-modules/postcss-modules-scope/blob/master/src/index.js) might be a good place to start.

**Comment by FrendEr** [comment]
@billyjanitsch  I am using css-loader@0.23.1 with css-modules, when I downgrading it to 0.14.1, it save 5~6s for me to build my project. But, I can't use css-modules anymore. Maybe the 5~6s time cost just because css-modules?

**Comment by ai** [comment]
Guys, just run postcss-devtools — it is a special profiling tool, to find slowest PostCSS plugins. Maybe it is a CSS minifier. Maybe it is some mistake in CSS Modules (honestly, this plugins have a lot of PostCSS APU violations, I create a issues for biggest mistakes).

Performance should always starts from profiling.

**Comment by MoOx** [comment]
@ai postcss instance is not public, so it's not possible to add postcss-devtools without editing the package directly :/

**Comment by ai** [comment]
Yeap, we need extra hacks. In this case we can just edit files inside `node_modules` :D

**Comment by psimyn** [comment]
Findings and hacks so far. Chain-hacking stuff in node_modules of actual project to try to get an idea of what is slow. @billyjanitsch let me know if you've found anything else - I'm at about the same point as your earlier post


Here's what I've done if anyone wants some setup/or if I forget. Paths all relative to main repo (which has webpack with css modules)

1.
```
cd node_modules/css-loader
npm install postcss-devtools
```

2. Hack devtools to handle modules-values
edit `node_modules/css-loader/postcss-devtools/node_modules/node_modules/text-table/index.js:59`, change c.length to `c && c.length || 0;` (or try/catch or something...).

3. Add devtools
node_modules/css-loader/lib/processCss.js
line 5 (new):  + var devtools = require('postcss-devtools');
line 152:  + devtools({precise: true}),

Some typical numbers:
```
postcss-modules-local-by-default  61.735718 ms
postcss-modules-scope             21.195637 ms
css-loader-parser                 13.432423 ms
modules-extract-imports           1.107515 ms
undefined                         659.907 μs
```



node_modules/css-loader/node_modules/postcss-modules-local-by-default/index.js
console.log timediffs throughout this file
line ~238 call to localizeDecl (inside forEach loop) is where it seems to spend most of it's time

Haven't yet dug much into that but will try to see if there is anything obvious

**Comment by ai** [comment]
Looks fine. Do we have slow performance in production or development mode (because production mode has also a CSS minifier)

**Comment by psimyn** [comment]
both - but in dev mode it's ~80% of the build time. Dev mode is the more frustrating one, since they run hundreds of times more frequently than production deploys.

Main contributor is a js entry point used as dumping ground for all CSS files (extract text plugin then generates single CSS file). If changing a file included in a lot of places (e.g. variable in settings) it's often 30-40s to rebuild (while running watch!).

**Comment by psimyn** [comment]
i noticed that even though 'postcss-modules' stuff was taking the longest, it was still in the order of milliseconds whereas the actual wait time was seconds. ran a trace with `node --prof ./node_modules/.bin/webpack`, then loaded it in chrome's about://tracing view

It showed a huge amount of time (~75%) was being spent in url-resolver's Rework calls, so probably not css-loader-related.

removing sourceMap from sass-loader options has given ~400% speedup (from sometimes minutes down to ~30 seconds). Subsequent profiles have been more balanced (mix of all loaders).

Can people try disabling sourcemaps and see if that improves. I will try to look into why it's having such an effect, or if there are some other optimisations for for loader

**Comment by MoOx** [comment]
The weird thing is that you are mentioning Rework. css-loader is supposed to use postcss, not rework.

**Comment by psimyn** [comment]
yeah rework was used by url-loader (I think), but some kind of knock-on effect due to sourcemaps

**Comment by jhnns** [comment]
@psimyn disabling source maps will *always* speed up the build time. But I have to admit that a 400% increase is a lot and there is probably room for optimization. 

Btw: the url-loader has never used rework. Remember, the url-loader is *not* responsible for detecting `url()` references in CSS-files. The url-loader does not know about CSS, HTML or JavaScript. It just takes a file, checks its file size and either emits it to the output folder and returns the final url or just returns a data url.

**Comment by psimyn** [comment]
my bad, resolve-url-loader had snuck himself in there - that is what was responsible for the rework process

I'll try to get a better profile of the postcss plugins since removing it

**Comment by jhnns** [comment]
No worries :grin:

**Comment by BerndWessels** [comment]
Hi

Any updates on the performance issues?

I use latest webpack with latest version of all loaders and plugins

    sassLoader: {
        loader: ExtractTextPlugin.extract('css?sourceMap&modules&importLoaders=2!postcss!resolve-url!sass')
        }

for the production build and it is terribly slow. Even though I have only about 6 small sass files imported it takes more than a minute on a decent core i7 win 10 with ssd.

**Comment by psimyn** [comment]
@BerndWessels my main suspect is UglifyJS plugin - can you try removing that from your `BUILD` block and see if any faster?

Do you have a sample repo set up for this? I have been meaning to look back into it but needed a good example (i.e. very slow build) to test on

Thanks!

**Comment by BerndWessels** [comment]
@psimyn You are right - removing the UglifyJsPlugin speeds up the production build extremely (90sec down to 30sec). But I am pretty sure that it was faster before even with the ulgify plugin.

I will do some more experiments and maybe share a test repo if I get stuck.

Thanks for now.

**Comment by datakurre** [comment]
014.5

Hash: 62722a60bab2439b5095
Version: webpack 1.13.1
Time: 6154ms

0.23.1

Hash: 17911a52a6e0f640d6ed
Version: webpack 1.13.1
Time: 390122ms

**Comment by psimyn** [comment]
@datakurre do you have an example project to try with?

**Comment by datakurre** [comment]
@psimyn Nothing public currently. I was just struggling with these slowing build times without any visible reason and then found this issue.

**Comment by psimyn** [comment]
no worries, I will try to get some more info with node inspect later this week. If you find any good open source examples of super long builds let me know :)

**Comment by datakurre** [comment]
@psimyn Thanks. My example will eventually be published, but it may still take a few weeks and is not a trivial setup (I'm working on a webpack build setup for theming an open source CMS called Plone, and I don't even know how many original less/css files my build currently has :). So, probably there are simpler examples out there.

**Comment by jhnns** [comment]
A complex example would actually be good. I think the performance issues are not noticeable in too simple setups. I've seen some real slow builds in the wild and I don't know why that is...

**Comment by psimyn** [comment]
I just tried some profiling with a single entry point that just requires js. Most time-consuming thing I found was babel-loader.

Original build:
babel-loader for js
css-loader and extract-text-plugin for css
~4500 line css file (repeated class) 
![image](https://cloud.githubusercontent.com/assets/1731922/16839305/bee5721e-4a11-11e6-9bfe-a275d5433358.png)

Same, but without babel-loader:
![image](https://cloud.githubusercontent.com/assets/1731922/16839338/ddfe17e6-4a11-11e6-9fd0-fbca88dfa35b.png)

Setting up a similar test [here](https://github.com/psimyn/science); I'll try making it similar, or at least take longer for testing

**Comment by jhnns** [comment]
Yes, it makes sense that the babel-loader is a heavy loader, that's why you should skip `node_modules`.

**Comment by sublimeye** [comment]
Guys, this problem still exists and babel-loader does not related.
I was struggling trying to optimize webpack build times and couldn't understand why the hack it happens with nano-500kb CSS file.

I created a separate repository where only required webpack plugins are used:
https://github.com/sublimeye/css-loader-slow-load-example

Whenever I switch back to css-loader 0.14.5 I have ~2seconds, when I switch to version 0.23 I get 80seconds. It's ridiculous how long this bug exists. I'll probably try to look myself what might trigger that enormous work.

**Comment by psimyn** [comment]
thanks @sublimeye! checked your example, 90% of the time is spent in postcss-discard-duplicates. Can you try with this in webpack config?

```
  loader: 'style!css?-discardDuplicates'
```

For me build went from 40s to ~5s

**Comment by jhnns** [comment]
> I'll probably try to look myself what might trigger that enormous work.

That is an excellent idea 👍. No one of us gets paid to do this kind of work. Our time is limited just as yours.

**Comment by ai** [comment]
Also maybe [postcss-csso](https://github.com/lahmatiy/postcss-csso) is better idea for CSS minify. It uses PostCSS AST too, but faster.

**Comment by asztal** [comment]
I've attempted to fix the postcss-discard-duplicates performance issues with https://github.com/ben-eb/postcss-discard-duplicates/pull/32. Perhaps someone could try replacing their `postcss-discard-duplicates` with [my version](https://github.com/asztal/postcss-discard-duplicates/tree/zoom-zoom) to see if it improves their CSS compile times?

**Comment by ben-eb** [comment]
I can confirm @asztal's patch dramatically improves performance and so I've cut a new release of postcss-discard-duplicates. New installs should see a drop in build times especially for large CSS files.

**Comment by csvan** [comment]
Confirming that `2.0.2` is a drastic improvement (builds down from 5-6 seconds to 2-3).

**Comment by flynfish** [comment]
same issue for me. Downgrading to 0.14.5 brought the build from about 40s down to under 2s.

**Comment by jonnolen** [comment]
dumb question, what is npm preferred way of pegging the version of postcss-discard-duplicates at 2.0.2?  I'm seeing it pulled in as via of cssnano dependencies.

**Comment by aight8** [comment]
How much this issue is solved? I just want that css loader work and do ONLY what it is related to. Postcss etc. I configure myself - how the most here except. Otherwise I have no clue what css-loader already doing and what not. This is extremly confusing then.

**Comment by bebraw** [comment]
@jonnolen Can you try to fix its version as a dev dep or lock it through yarn?

@aight8 Not solved at all, the regression still remains. It would take a bigger redesign to solve this I think and you still might see some slowness (the old solution was bit of a hack, but it was fast, yup).

**Comment by kennethaa** [comment]
Downgraded css-loader from 0.26.1 to 0.14.5 and our total build time (including npm install, npm build, rsync and mco) went from 16 minutes to 8 and 23 seconds in Jenkins. This is just crazy.

**Comment by jhnns** [comment]
I did some profiling with the sass-loader: https://github.com/webpack-contrib/sass-loader/issues/296#issuecomment-288464857

**Comment by knaos** [comment]
Is this issue fixed yet?

**Comment by outreal** [comment]
Does this issue also affect webpack 2 or 3?

**Comment by jhnns** [comment]
Nope, afaik it's not fixed. It's not directly related to webpack itself, but the way how the css loader works.

**Comment by evilebottnawi** [comment]
Feel free to PR, what speedup css loader

**Comment by yibn2008** [comment]
If you don't need sourceMap and css module, you can try [fast-css-loader](https://github.com/yibn2008/fast-css-loader), it use RegExp to parse `@import` and `url(...)`, which will be faster than postcss.

**Comment by ai** [comment]
@yibn2008 note, that regexp is not a safe way for CSS since CSS could contain a string (inlined SVG?) or comments with directives inside.

But it is a good idea to improve css-loader. Maybe we could try to create a css-loader fork with PostCSS (it’s parser is very fast), but without all features. Maybe CSS Modules is used every time and slow down the process?

**Comment by yibn2008** [comment]
@ai I have handled comments in css, but inline SVG haven't been tested. I'll try to use postcss alone later to see is the performance improved.

**Comment by evilebottnawi** [comment]
@ai it is in our plans in future, if somebody started this i can help

**Comment by evilebottnawi** [comment]
In next major release (will be release in next future):
- We implement reusing `ast` from `postcss-loader` (increase perf)
- We implement logic for disable `css` modules plugins (`modules: false`, by default `css` modules disabled, you can avoid `modules: false`), it is allow increase perf, if you don't use `css` modules.

Feel free to open issue if you have ideas how we can increase perf more

**Comment by ZuBB** [comment]
@evilebottnawi will be any limitation for minimal required version of webpack for this new release of css-loader?

**Comment by evilebottnawi** [comment]
@ZuBB `webpack@4`, but you can ignore `peerDependencies` warning and use in `webpack@3`
