### ISSUE TITLE
css-loader > 0.27.2 breaks webpack compilation

### ISSUE THREAD

**Issue by karolyi** [webpack-contrib/css-loader#460]
**What is the current behavior?**
Hey,

after testing it out, using `css-loader` version greater than `0.27.2` breaks my webpack compilation. `master` still has it.I get errors saying
`Module build failed: TypeError: $export is not a function`
then a lot of traceback, and then at the end:
`blabla.scss doesn't export content`

**If the current behavior is a bug, please provide the steps to reproduce.**
Install any lastest webpack with css-loader, and use my provided config here:
https://github.com/karolyi/forum-django

**What is the expected behavior?**
To compile right?

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
I use the latest stuff (ignore my package.json on the repo, that got upgraded but not pushed yet)
It happens on my dev ubuntu virtual machine.

Until this gets fixed, I'll need to pin the css-loader version to 0.27.2

**Comment by bebraw** [comment]
Possibly related commit based on Git history, https://github.com/webpack-contrib/css-loader/commit/4250129cc39b75b3e894c3a30401ef47b931863d .

I might get to this sometime next week perhaps.

**Comment by karolyi** [comment]
Update: seems to have fixed in `0.28.0`.

Cheers guys

**Comment by infeng** [comment]
I still have this error in `0.28.0`.
My webpack config:
```javascript
      {
        test(filePath) {
          return /\.css$/.test(filePath) && !/\.module\.css$/.test(filePath);
        },
        loader: ExtractTextPlugin.extract({
          use: [{
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          }]}),
      },
```

In My application:
```javascript
import styls from  './style.css';
```

**Comment by karolyi** [comment]
@infeng do you use the latest version from all dependencies/packages?

use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to update.

**Comment by infeng** [comment]
I use  `npm-check-updates`, all dependencies use the latest version.

**Comment by infeng** [comment]
When I use `extract-text-webpack-plugin` and `css-loader` together, it get error.
